### ISSUE TITLE
3D viewer locks up in Crosshair Plugin

### ISSUE THREAD

**Issue by NicoleSchieber** [automated-ultramicrotomy/crosshair#19]
When I have a file open in Crosshair as soon as I try to move the model in the 3D viewer it locks up and I have to close and try again. This happens consistently, maybe 1 in 10 I manage to be able to manipulate the model in the 3D viewer. It comes with the message that FIJI wants access to record the computers screen. I have attached this message as well as the view of my computer where this option looks to me that I have accepted already? I am doing this on a MacOS Monterey Version 12.6. My FIJI is IMAGEj2 version 2.9.0/1.54f.

Do you need more information?

Error messages:
3D [dev] 1.6.0-scijava-2-pre11-daily-experimental daily

nFrames = 1
Keymap list file /Users/uqnschie/Library/Application Support/sc.fiji.bigdataviewer/keymaps/keymaps.yaml not found. Using builtin styles.
Appearance settings file /Users/uqnschie/Library/Application Support/sc.fiji.bigdataviewer/appearance.yaml not found. Using defaults.
com.jogamp.opengl.GLException: detachAllImpl failed: FBO implementation fault, FBO[name r/w 2/2, init true, bound true, size 512x534, samples 0/4, modified true/true, depth RenderAttachment[type DEPTH, format 0x81a5, samples 0, 512x534, name 0xffffffff, obj 0x66ccf30c], stencil null, colorbuffer attachments: 1/8, with 1 textures: [TextureAttachment[type COLOR_TEXTURE, target GL_TEXTURE_2D, level 0, format 0x8051, 512x534, border 0, dataFormat 0x1907, dataType 0x1401; min/mag 0x2600/0x2600, wrap S/T 0x812f/0x812f; name 0xffffffff, obj 0x3b336a82], null, null, null, null, null, null, null], msaa[null, hasSink false, dirty true], state FBO implementation fault, obj 0x468be22d]
	at com.jogamp.opengl.FBObject.detachAllImpl(FBObject.java:2250)
	at com.jogamp.opengl.FBObject.reset(FBObject.java:1191)
	at org.scijava.java3d.JoglPipeline.resizeOffscreenLayer(JoglPipeline.java:6290)
	at org.scijava.java3d.Canvas3D.setView
port(Canvas3D.java:4864)
	at org.scijava.java3d.Renderer.doWork(Renderer.java:993)
	at org.scijava.java3d.J3dThread.run(J3dThread.java:271)
Exception occurred in RenderingErrorListener:
java.lang.RuntimeException
	at ij3d.ImageWindow3D$ErrorListener.errorOccurred(ImageWindow3D.java:351)
	at org.scijava.java3d.VirtualUniverse.notifyRenderingErrorListeners(VirtualUniverse.java:1198)
	at org.scijava.java3d.NotificationThread.processNotifications(NotificationThread.java:86)
	at org.scijava.java3d.NotificationThread.run(NotificationThread.java:104)

<img width="464" alt="CrosshairError_1" src="https://github.com/automated-ultramicrotomy/crosshair/assets/141792312/126650bb-878c-4ed3-b3d7-b7c590020778">

<img width="612" alt="RecordPermission" src="https://github.com/automated-ultramicrotomy/crosshair/assets/141792312/cb75e2e8-a0f2-42fa-a939-45653613adf2">

**Comment by K-Meech** [comment]
Thanks for the info @NicoleSchieber ! 
Could you also let me know which other update sites you have enabled in Fiji? If you download a new Fiji (and put it in a separate folder to your usual one) + only enable the Crosshair update site - do you still get the same errors?

**Comment by NicoleSchieber** [comment]
Hi Kimberly,

I have since found that if I don’t resize the 3D viewer (although this is annoying) and press deny on the request for screen record I can use crosshair properly.

I have updated FIJI and there was a lot that updated including 3D viewer (ticked is ImageJ, Fiji, Java-8, and crosshair). After update on my original version I get the same problems.

In the second version of FIJI (ticked is ImageJ, Fiji, Java-8, and crosshair) – do you mean for me to untick the first 3? With these selected I still got the screen record message and on resizing the 3D viewer it locks up and I have to close everything and reopen. If I don’t resize the viewer I can work with it.

This is the log when I try to change the size of the 3D viewer window:
3D [dev] 1.6.0-scijava-2-pre11-daily-experimental daily

nFrames = 1
Keymap list file /Users/uqnschie/Library/Application Support/sc.fiji.bigdataviewer/keymaps/keymaps.yaml not found. Using builtin styles.
Appearance settings file /Users/uqnschie/Library/Application Support/sc.fiji.bigdataviewer/appearance.yaml not found. Using defaults.
com.jogamp.opengl.GLException: detachAllImpl failed: FBO implementation fault, FBO[name r/w 2/2, init true, bound true, size 671x640, samples 0/4, modified true/true, depth RenderAttachment[type DEPTH, format 0x81a5, samples 0, 671x640, name 0xffffffff, obj 0x11353fb3], stencil null, colorbuffer attachments: 1/8, with 1 textures: [TextureAttachment[type COLOR_TEXTURE, target GL_TEXTURE_2D, level 0, format 0x8051, 671x640, border 0, dataFormat 0x1907, dataType 0x1401; min/mag 0x2600/0x2600, wrap S/T 0x812f/0x812f; name 0xffffffff, obj 0x111bbc64], null, null, null, null, null, null, null], msaa[null, hasSink false, dirty true], state FBO implementation fault, obj 0x138b60f8]
                at com.jogamp.opengl.FBObject.detachAllImpl(FBObject.java:2250)
                at com.jogamp.opengl.FBObject.reset(FBObject.java:1191)
                at org.scijava.java3d.JoglPipeline.resizeOffscreenLayer(JoglPipeline.java:6290)
                at org.scijava.java3d.Canvas3D.setViewport(Canvas3D.java:4864)
                at org.scijava.java3d.Renderer.doWork(Renderer.java:993)
                at org.scijava.java3d.J3dThread.run(J3dThread.java:271)
Exception occurred in RenderingErrorListener:
java.lang.RuntimeException
                at ij3d.ImageWindow3D$ErrorListener.errorOccurred(ImageWindow3D.java:351)
                at org.scijava.java3d.VirtualUniverse.notifyRenderingErrorListeners(VirtualUniverse.java:1198)
                at org.scijava.java3d.NotificationThread.processNotifications(NotificationThread.java:86)
                at org.scijava.java3d.NotificationThread.run(NotificationThread.java:104)


Best,
Nicole.

Nicole Schieber (Hall)
Laboratory Manager - Electron Microscopy for Life-Science & Soft Matter

Centre for Microscopy and Microanalysis
Level 1, AIBN Building (#75)
Cnr College & Cooper Roads
The University of Queensland
St Lucia
Brisbane QLD 4072 Australia

Email: ***@***.******@***.***>
Tel:  +61 7 3346 3985
Mobile: +61 487 788 387
http://www.cmm.uq.edu.au<http://www.cmm.uq.edu.au/>
https://www.linkedin.com/in/nicole-schieber-997b7970/
http://www.twitter.com/NicoleSchieber

In the office Monday to Friday

I acknowledge the traditional custodians of the land on which I am working, and pay my respects to Elders, past and present.

[signature_2290910474]



The University of Queensland is embracing the Green Office philosophy. Please consider the environment before printing this email.
This email (including any attached files) is intended solely for the addressee and may contain confidential information of
The University of Queensland. If you are not the addressee, you are notified that any transmission, distribution, printing
or photocopying of this email is prohibited. If you have received this email in error, please delete and notify me.
Unless explicitly stated, the opinions expressed in this email do not represent the official position of The University of Queensland.

From: Kimberly Meechan ***@***.***>
Reply to: automated-ultramicrotomy/crosshair ***@***.***>
Date: Wednesday, 9 August 2023 at 7:18 pm
To: automated-ultramicrotomy/crosshair ***@***.***>
Cc: Nicole Hall ***@***.***>, Mention ***@***.***>
Subject: Re: [automated-ultramicrotomy/crosshair] 3D viewer locks up in Crosshair Plugin (Issue #19)


Thanks for the info @NicoleSchieber<https://github.com/NicoleSchieber> !
Could you also let me know which other update sites you have enabled in Fiji? If you download a new Fiji (and put it in a separate folder to your usual one) + only enable the Crosshair update site - do you still get the same errors?

**Comment by K-Meech** [comment]
Thanks @NicoleSchieber - that's perfect. Good to know that you get the same errors in an updated + new Fiji. 
I'll look into this soon and see if I can find a solution for the resizing problem.

**Comment by K-Meech** [comment]
So I looked into this some more and unfortunately this seems to be a known issue with the ImageJ 3D Viewer on Macs:
https://forum.image.sc/t/crash-with-fiji-3d-viewer-plugin-on-mac-upon-any-window-resizing/35323
https://forum.image.sc/t/3d-viewer-crashes-when-resizing-the-window/11829/5

As it's an issue with the external 3D viewer code, there's no simple fix unfortunately. At some point, it would make sense to update from using the 3D Viewer to SciView (which is a more recent 3D viewer). I won't have time to do this in the near future though, as it's a big change. Sorry I can't be of more help @NicoleSchieber ! I'll let you know if I find time to check out SciView as an alternative.

**Comment by NicoleSchieber** [comment]
Thanks Kimberly,

That is good to know in a way that is a known error. Thanks so much for looking into it!

Best,
Nicole.

Nicole Schieber (Hall)
Laboratory Manager - Electron Microscopy for Life-Science & Soft Matter

Centre for Microscopy and Microanalysis
Level 1, AIBN Building (#75)
Cnr College & Cooper Roads
The University of Queensland
St Lucia
Brisbane QLD 4072 Australia

Email: ***@***.******@***.***>
Tel:  +61 7 3346 3985
Mobile: +61 487 788 387
http://www.cmm.uq.edu.au<http://www.cmm.uq.edu.au/>
https://www.linkedin.com/in/nicole-schieber-997b7970/
http://www.twitter.com/NicoleSchieber

In the office Monday to Friday

I acknowledge the traditional custodians of the land on which I am working, and pay my respects to Elders, past and present.

[signature_2225992706]



The University of Queensland is embracing the Green Office philosophy. Please consider the environment before printing this email.
This email (including any attached files) is intended solely for the addressee and may contain confidential information of
The University of Queensland. If you are not the addressee, you are notified that any transmission, distribution, printing
or photocopying of this email is prohibited. If you have received this email in error, please delete and notify me.
Unless explicitly stated, the opinions expressed in this email do not represent the official position of The University of Queensland.

From: Kimberly Meechan ***@***.***>
Reply to: automated-ultramicrotomy/crosshair ***@***.***>
Date: Monday, 14 August 2023 at 3:45 am
To: automated-ultramicrotomy/crosshair ***@***.***>
Cc: Nicole Hall ***@***.***>, Mention ***@***.***>
Subject: Re: [automated-ultramicrotomy/crosshair] 3D viewer locks up in Crosshair Plugin (Issue #19)


So I looked into this some more and unfortunately this seems to be a known issue with the ImageJ 3D Viewer on Macs:
https://forum.image.sc/t/crash-with-fiji-3d-viewer-plugin-on-mac-upon-any-window-resizing/35323
https://forum.image.sc/t/3d-viewer-crashes-when-resizing-the-window/11829/5

As it's an issue with the external 3D viewer code, there's no simple fix unfortunately. At some point, it would make sense to update from using the 3D Viewer to SciView (which is a more recent 3D viewer). I won't have time to do this in the near future though, as it's a big change. Sorry I can't be of more help @NicoleSchieber<https://github.com/NicoleSchieber> ! I'll let you know if I find time to check out SciView as an alternative.
