### ISSUE TITLE
Cutting mode errors with initial knife and tilt of zero

### ISSUE THREAD

**Issue by K-Meech** [automated-ultramicrotomy/crosshair#26]
Entering cutting mode with all settings at zero (initial knife / tilt + all solution parameters) results in `Cutting mode inactive` being printed when the cutting depth slider is moved.

It also prints a long list of errors:
```
Exception in thread "AWT-EventQueue-0" java.lang.NegativeArraySizeException
	at ij3d.shapes.BoundingBox.makeLine(BoundingBox.java:209)
	at ij3d.shapes.BoundingBox.<init>(BoundingBox.java:120)
	at ij3d.shapes.BoundingBox.<init>(BoundingBox.java:54)
	at ij3d.shapes.BoundingBox.<init>(BoundingBox.java:50)
	at ij3d.ContentInstant.display(ContentInstant.java:236)
	at ij3d.ContentCreator.createContent(ContentCreator.java:132)
	at ij3d.ContentCreator.createContent(ContentCreator.java:119)
	at ij3d.Image3DUniverse.createContent(Image3DUniverse.java:1175)
	at ij3d.Image3DUniverse.addCustomMesh(Image3DUniverse.java:1143)
	at de.embl.schwab.crosshair.microtome.Cutting.initialiseCuttingPlane(Cutting.java:95)
	at de.embl.schwab.crosshair.microtome.MicrotomeManager.enterCuttingMode(MicrotomeManager.java:144)
	at de.embl.schwab.crosshair.ui.swing.MicrotomePanel.enterCuttingMode(MicrotomePanel.java:454)
	at de.embl.schwab.crosshair.ui.swing.MicrotomePanel.access$100(MicrotomePanel.java:21)
	at de.embl.schwab.crosshair.ui.swing.MicrotomePanel$cuttingModeListener.actionPerformed(MicrotomePanel.java:378)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by K-Meech** [comment]
This is related to this issue on the 3D viewer: https://github.com/fiji/3D_Viewer/issues/35 . When the `knife angle` is 0, the created cutting plane will be perfectly perpendicular to the y axis. The 3D viewer then attempts to draw a 3D bounding box, including lines in the y direction which will have a length of zero (as our plane has no thickness in y). This can result in `NegativeArraySizeException`.

**Comment by K-Meech** [comment]
This isn't limited to a knife angle of 0, it also occurs up to around 0.5 degrees. I should add two more scenarios to my `MicrotomeManagerTestProviders/cuttingProvider` for:
- 0 degree knife angle
- 0.5 degree knife angle
